#ifndef FILTERLIBCONFIG_H
#define FILTERLIBCONFIG_H

#include "pro_config.h"

#define SERVER_PATH FILTER_TRANS_PATH

//#define LOCKER_EXE LOCKER_UI

#define EXE_NAME EXE_FILTERLIB_NAME

//#define FILTERUIEXE_DIR APP_PATH

#define LOG_FILE_NAME LOG_FILTERLIB_FILE

#endif // FILTERLIBCONFIG_H
